// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrNQFEJSThROWIDnFZfplgYZcUcYVBxhQ',
    appId: '1:689237829129:web:352528f2faced588a2bad8',
    messagingSenderId: '689237829129',
    projectId: 'mr-hanafy-project',
    authDomain: 'mr-hanafy-project.firebaseapp.com',
    storageBucket: 'mr-hanafy-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNQFEJSThROWIDnFZfplgYZcUcYVBxhQ',
    appId: '1:689237829129:android:352528f2faced588a2bad8',
    messagingSenderId: '689237829129',
    projectId: 'mr-hanafy-project',
    storageBucket: 'mr-hanafy-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00vck-eLwowYwRtW1rPS30RIVzzZurEg',
    appId: '1:689237829129:ios:e31a1927ef3baa6ba2bad8',
    messagingSenderId: '689237829129',
    projectId: 'mr-hanafy-project',
    storageBucket: 'mr-hanafy-project.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00vck-eLwowYwRtW1rPS30RIVzzZurEg',
    appId: '1:689237829129:ios:e31a1927ef3baa6ba2bad8',
    messagingSenderId: '689237829129',
    projectId: 'mr-hanafy-project',
    storageBucket: 'mr-hanafy-project.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrNQFEJSThROWIDnFZfplgYZcUcYVBxhQ',
    appId: '1:689237829129:web:352528f2faced588a2bad8',
    messagingSenderId: '689237829129',
    projectId: 'mr-hanafy-project',
    authDomain: 'mr-hanafy-project.firebaseapp.com',
    storageBucket: 'mr-hanafy-project.firebasestorage.app',
  );
}
